apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerScaleSet
metadata:
  name: bankapp-scaleset
spec:
  # Same as deployment
  repository: Vaibhav67897/Springboot-BankApp
  minRunners: 1
  maxRunners: 10  # Job load pe scale
  template:
    spec:
      dockerEnabled: true
      # labels, resources etc.

