apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: bankapp-runner
spec:
  replicas: 10
  template:
    spec:
      repository: Vaibhav67897/Springboot-BankApp
      dockerEnabled: true
      privileged: true
      resources:
        requests:
          cpu: "1"
          memory: 2Gi
        limits:
          cpu: "4"
          memory: 8Gi
      labels: ["self-hosted", "docker"]

